components:
  schemas:
    osvAffected:
      description: Affected versions and commits.
      properties:
        databaseSpecific:
          description: 'Optional. JSON object holding additional information about
            the

            vulnerability as defined by the database for which the record applies.'
          properties: {}
          type: object
        ecosystemSpecific:
          description: 'Optional. JSON object holding additional information about
            the

            vulnerability as defined by the ecosystem for which the record applies.'
          properties: {}
          type: object
        package:
          $ref: '#/components/schemas/osvPackage'
        ranges:
          description: Required. Range information.
          items:
            $ref: '#/components/schemas/osvRange'
          type: array
        severity:
          description: Optional. Severity of the vulnerability for this package.
          items:
            $ref: '#/components/schemas/osvSeverity'
          type: array
        versions:
          description: Optional. List of affected versions.
          items:
            type: string
          type: array
      type: object
    osvCredit:
      properties:
        contact:
          description: Contact methods (URLs).
          items:
            type: string
          type: array
        name:
          description: The name to give credit to.
          type: string
        type:
          $ref: '#/components/schemas/osvCreditType'
      type: object
    osvCreditType:
      default: UNSPECIFIED
      enum:
      - UNSPECIFIED
      - OTHER
      - FINDER
      - REPORTER
      - ANALYST
      - COORDINATOR
      - REMEDIATION_DEVELOPER
      - REMEDIATION_REVIEWER
      - REMEDIATION_VERIFIER
      - TOOL
      - SPONSOR
      type: string
    osvEvent:
      description: Version events.
      properties:
        fixed:
          description: The version/commit that this vulnerability was fixed in.
          type: string
        introduced:
          description: 'The earliest version/commit where this vulnerability

            was introduced in.'
          type: string
        lastAffected:
          description: The last affected version.
          type: string
        limit:
          description: The limit to apply to the range.
          type: string
      type: object
    osvPackage:
      description: Package information and version.
      properties:
        ecosystem:
          description: "Required. The ecosystem for this package. \nFor the complete\
            \ list of valid ecosystem names, see\n<https://ossf.github.io/osv-schema/#affectedpackage-field>."
          type: string
        name:
          description: 'Required. Name of the package. Should match the name used
            in the package

            ecosystem (e.g. the npm package name). For C/C++ projects integrated in

            OSS-Fuzz, this is the name used for the integration.'
          type: string
        purl:
          description: Optional. The package URL for this package.
          type: string
      type: object
    osvRange:
      description: Affected ranges.
      properties:
        events:
          description: Required. Version event information.
          items:
            $ref: '#/components/schemas/osvEvent'
          type: array
        repo:
          description: 'Required if type is GIT. The publicly accessible URL of the
            repo that can

            be directly passed to clone commands.'
          type: string
        type:
          $ref: '#/components/schemas/osvRangeType'
      type: object
    osvRangeType:
      default: UNSPECIFIED
      description: Type of the version information.
      enum:
      - UNSPECIFIED
      - GIT
      - SEMVER
      - ECOSYSTEM
      type: string
    osvReference:
      description: Reference URL.
      properties:
        type:
          $ref: '#/components/schemas/osvReferenceType'
        url:
          description: Required. The URL.
          type: string
      type: object
    osvReferenceType:
      default: NONE
      enum:
      - NONE
      - WEB
      - ADVISORY
      - REPORT
      - FIX
      - PACKAGE
      - ARTICLE
      - EVIDENCE
      type: string
    osvSeverity:
      properties:
        score:
          description: The quantitative score.
          type: string
        type:
          $ref: '#/components/schemas/osvSeverityType'
      type: object
    osvSeverityType:
      default: UNSPECIFIED
      description: Type of the severity.
      enum:
      - UNSPECIFIED
      - CVSS_V4
      - CVSS_V3
      - CVSS_V2
      type: string
    osvVulnerability:
      description: 'A vulnerability entry.

        The protobuf representation is *NOT* stable and only used for implementing

        the JSON based API.'
      properties:
        affected:
          description: Required. Affected commit ranges and versions.
          items:
            $ref: '#/components/schemas/osvAffected'
          type: array
        aliases:
          description: Optional. IDs for the same vulnerability in other databases.
          items:
            type: string
          type: array
        credits:
          description: Optional. Credits for the vulnerability.
          items:
            $ref: '#/components/schemas/osvCredit'
          type: array
        databaseSpecific:
          description: 'Optional. JSON object holding additional information about
            the

            vulnerability as defined by the database for which the record applies.'
          properties: {}
          type: object
        details:
          description: Required. Any additional human readable details for the vulnerability.
          type: string
        id:
          description: "The `id` field is a unique identifier for the vulnerability\
            \ entry. It is a\nstring of the format `<DB>-<ENTRYID>`, where `DB` names\
            \ the database and\n`ENTRYID` is in the format used by the database. For\
            \ example:\n\u201COSV-2020-111\u201D, \u201CCVE-2021-3114\u201D, or \u201C\
            GHSA-vp9c-fpxx-744v\u201D."
          type: string
        modified:
          description: The RFC3339 timestamp indicating when this entry was last modified.
          format: date-time
          type: string
        published:
          description: The RFC3339 timestamp indicating when this entry was published.
          format: date-time
          type: string
        references:
          description: 'Optional. URLs to more information/advisories (including the

            scheme e.g "https://").'
          items:
            $ref: '#/components/schemas/osvReference'
          type: array
        related:
          description: 'Optional. List of IDs of closely related vulnerabilities,
            such as the same

            problem in alternate ecosystems.'
          items:
            type: string
          type: array
        schemaVersion:
          description: The OSV schema version.
          type: string
        severity:
          description: Optional. Severity of the vulnerability.
          items:
            $ref: '#/components/schemas/osvSeverity'
          type: array
        summary:
          description: 'Required. One line human readable summary for the vulnerability.
            It is

            recommended to keep this under 120 characters.'
          type: string
        withdrawn:
          description: 'Optional. The RFC3339 timestamp indicating when this entry
            is considered to

            be withdrawn.'
          format: date-time
          type: string
      type: object
    protobufAny:
      properties:
        typeUrl:
          type: string
        value:
          format: byte
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
      type: object
    protobufNullValue:
      default: NULL_VALUE
      description: "`NullValue` is a singleton enumeration to represent the null value\
        \ for the\n`Value` type union.\n\n The JSON representation for `NullValue`\
        \ is JSON `null`.\n\n - NULL_VALUE: Null value."
      enum:
      - NULL_VALUE
      type: string
    rpcStatus:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
        message:
          type: string
      type: object
    v1BatchQuery:
      description: Batch query format.
      properties:
        queries:
          description: The queries that form this batch query.
          items:
            $ref: '#/components/schemas/v1Query'
          type: array
      type: object
    v1BatchVulnerabilityList:
      description: Batched lists of Vulnerability entries.
      properties:
        results:
          items:
            $ref: '#/components/schemas/v1VulnerabilityList'
          type: array
      type: object
    v1FileHash:
      description: 'Information about the files in the repository

        to identify the version.'
      properties:
        filePath:
          description: The file path inside the repository, relative to the repository
            root.
          type: string
        hash:
          format: byte
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
        hashType:
          type: string
      type: object
    v1Query:
      description: Query format.
      properties:
        commit:
          description: The commit hash to query for. If specified, `version` should
            not be set.
          type: string
        package:
          $ref: '#/components/schemas/osvPackage'
        pageToken:
          type: string
        version:
          description: 'The version string to query for. A fuzzy match is done against
            upstream

            versions. If specified, `commit` should not be set.'
          type: string
      type: object
    v1VersionMatch:
      description: Match information for the provided VersionQuery.
      properties:
        cpe23:
          description: CPE 2.3.
          type: string
        osvIdentifier:
          $ref: '#/components/schemas/osvPackage'
        repoInfo:
          $ref: '#/components/schemas/v1VersionRepositoryInformation'
        score:
          description: Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
          format: double
          type: number
      type: object
    v1VersionMatchList:
      description: Result of DetmineVersion.
      properties:
        matches:
          items:
            $ref: '#/components/schemas/v1VersionMatch'
          type: array
      type: object
    v1VersionQuery:
      description: The version query.
      properties:
        fileHashes:
          items:
            $ref: '#/components/schemas/v1FileHash'
          type: array
        name:
          description: The name of the dependency. Can be empty.
          type: string
      type: object
    v1VersionRepositoryInformation:
      properties:
        address:
          description: Source address of the repository.
          type: string
        commit:
          description: Commit hash.
          format: byte
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
        tag:
          title: Commit tag
          type: string
        type:
          $ref: '#/components/schemas/v1VersionRepositoryInformationRepoType'
        version:
          title: Parsed version from commit tag
          type: string
      type: object
    v1VersionRepositoryInformationRepoType:
      default: UNSPECIFIED
      enum:
      - UNSPECIFIED
      - GIT
      type: string
    v1VulnerabilityList:
      description: A list of Vulnerability entries.
      properties:
        nextPageToken:
          type: string
        vulns:
          items:
            $ref: '#/components/schemas/osvVulnerability'
          type: array
      type: object
info:
  title: OSV
  version: '1.0'
openapi: 3.0.1
paths:
  /v1/query:
    post:
      operationId: OSV_QueryAffected
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1Query'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1VulnerabilityList'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: 'Query vulnerabilities for a particular project at a given commit or

        version.'
      tags:
      - OSV
      x-codegen-request-body-name: body
  /v1/querybatch:
    post:
      operationId: OSV_QueryAffectedBatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1BatchQuery'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1BatchVulnerabilityList'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: 'Query vulnerabilities (batched) for given package versions and commits.

        This currently allows a maximum of 1000 package versions to be included in
        a single query.'
      tags:
      - OSV
      x-codegen-request-body-name: body
  /v1/vulns/{id}:
    get:
      operationId: OSV_GetVulnById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/osvVulnerability'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Return a `Vulnerability` object for a given OSV ID.
      tags:
      - OSV
  /v1experimental/determineversion:
    post:
      operationId: OSV_DetermineVersion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1VersionQuery'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1VersionMatchList'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Determine the version of the provided hash values.
      tags:
      - OSV
      x-codegen-request-body-name: body
servers:
- url: //api.osv.dev/
x-original-swagger-version: '2.0'
